routes.count: "5"
routes.Schedule: "30"

# Route 1
routes.0.routeName: "Route1"
routes.0.routeStatus: "active"
routes.0.source.host: "eu-central-1.sftpcloud.io"
routes.0.source.port: "22"
routes.0.source.username: "3bf1f8ecb6b348db90aac30b68ca64d6"
routes.0.source.password: "sUvUlEaeqpcOOmbZ3wwP2oQ42eVjPBHu"
routes.0.source.path: "source1"
routes.0.destination.host: "eu-central-1.sftpcloud.io"
routes.0.destination.port: "22"
routes.0.destination.username: "1ee3ea5baaa443a2a4d632f7a40053a2"
routes.0.destination.password: "nt6b0xA57x1GCworY7BzfyNKW3j2R3lu"
routes.0.destination.path: "destination1"

# Route 2
routes.1.routeName: "Route2"
routes.1.routeStatus: "inactive"
routes.1.source.host: "eu-central-1.sftpcloud.io"
routes.1.source.port: "22"
routes.1.source.username: "3bf1f8ecb6b348db90aac30b68ca64d6"
routes.1.source.password: "sUvUlEaeqpcOOmbZ3wwP2oQ42eVjPBHu"
routes.1.source.path: "source2"
routes.1.destination.host: "eu-central-1.sftpcloud.io"
routes.1.destination.port: "22"
routes.1.destination.username: "1ee3ea5baaa443a2a4d632f7a40053a2"
routes.1.destination.password: "nt6b0xA57x1GCworY7BzfyNKW3j2R3lu"
routes.1.destination.path: "destination2"

# Route 3
routes.2.routeName: "Route3"
routes.2.routeStatus: "active"
routes.2.source.host: "eu-central-1.sftpcloud.io"
routes.2.source.port: "22"
routes.2.source.username: "3bf1f8ecb6b348db90aac30b68ca64d6"
routes.2.source.password: "sUvUlEaeqpcOOmbZ3wwP2oQ42eVjPBHu"
routes.2.source.path: "source3"
routes.2.destination.host: "eu-central-1.sftpcloud.io"
routes.2.destination.port: "22"
routes.2.destination.username: "1ee3ea5baaa443a2a4d632f7a40053a2"
routes.2.destination.password: "nt6b0xA57x1GCworY7BzfyNKW3j2R3lu"
routes.2.destination.path: "destination3"

# Route 4
routes.3.routeName: "Route4"
routes.3.routeStatus: "inactive"
routes.3.source.host: "eu-central-1.sftpcloud.io"
routes.3.source.port: "22"
routes.3.source.username: "3bf1f8ecb6b348db90aac30b68ca64d6"
routes.3.source.password: "sUvUlEaeqpcOOmbZ3wwP2oQ42eVjPBHu"
routes.3.source.path: "source4"
routes.3.destination.host: "eu-central-1.sftpcloud.io"
routes.3.destination.port: "22"
routes.3.destination.username: "1ee3ea5baaa443a2a4d632f7a40053a2"
routes.3.destination.password: "nt6b0xA57x1GCworY7BzfyNKW3j2R3lu"
routes.3.destination.path: "destination4"

# Route 5
routes.4.routeName: "Route5"
routes.4.routeStatus: "active"
routes.4.source.host: "eu-central-1.sftpcloud.io"
routes.4.source.port: "22"
routes.4.source.username: "3bf1f8ecb6b348db90aac30b68ca64d6"
routes.4.source.password: "sUvUlEaeqpcOOmbZ3wwP2oQ42eVjPBHu"
routes.4.source.path: "source5"
routes.4.destination.host: "eu-central-1.sftpcloud.io"
routes.4.destination.port: "22"
routes.4.destination.username: "1ee3ea5baaa443a2a4d632f7a40053a2"
routes.4.destination.password: "nt6b0xA57x1GCworY7BzfyNKW3j2R3lu"
routes.4.destination.path: "destination5"
